services:
  - type: web
    name: packet-analyzer
    runtime: python
    buildCommand: pip install -r Packet_analyzer-main/requirements.txt && chmod +x Packet_analyzer-main/dpi_engine
    startCommand: python Packet_analyzer-main/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
